- modules/CMakeLists.txt
- src/BYOD.cpp
- src/BYOD.h
- src/gui/utils/SettingsButton.cpp
- src/gui/utils/SettingsButton.h
> Add global setting for optionally using OpenGL renderring context

- src/CMakeLists.txt
- src/processors/ProcessorStore.cpp
- src/processors/other/Gate.cpp
- src/processors/other/Gate.h
> Add a gate processor

- CMakeLists.txt
- src/BYOD.cpp
We can move back to a newer version of JUCE once juce-framework/juce#984 get's fixed.
> Revert to JUCE version 6.1.2 for iOS PopupMenu fix

- CHANGELOG.md
- manual/Manual.md
- modules/CMakeLists.txt
- src/BYOD.cpp
- src/BYOD.h
- src/gui/utils/SettingsButton.cpp
- src/gui/utils/SettingsButton.h
> Use OpenGL by default, unless it is not available on the host system

- src/processors/drive/metal_face/MetalFaceRNN.cpp
> MetalFace: fix stuttering at higher sample rates

- src/gui/presets/PresetsComp.cpp
- src/gui/presets/PresetsComp.h
- src/processors/chain/ChainIOProcessor.cpp
- src/processors/chain/ChainIOProcessor.h
- src/processors/chain/ProcessorChainStateHelper.cpp
- src/state/presets/PresetManager.cpp
- src/state/presets/PresetManager.h
> Fix undo/redo bug with preset manager

- src/CMakeLists.txt
- src/processors/ProcessorStore.cpp
- src/processors/other/Rotary.cpp
- src/processors/other/Rotary.h
> First draft of rotary effect

- src/processors/drive/Warp.h
- src/processors/drive/big_muff/BigMuffClippingStage.cpp
- src/processors/drive/centaur/AmpStage.h
- src/processors/drive/centaur/InputBufferProcessor.cpp
- src/processors/drive/centaur/OutputStageProcessor.cpp
- src/processors/drive/centaur/SummingAmp.h
- src/processors/drive/king_of_tone/KingOfToneDrive.cpp
- src/processors/tone/BassCleaner.h
- src/processors/tone/BigMuffTone.h
- src/processors/tone/HighCut.h
- src/processors/tone/TrebleBooster.h
Think I got all the spots where the filter order should be changed, let me know if I missed anything.
Thanks!
> Corresponding changes to bilinear filters

- src/processors/tone/AmpIRs.cpp
- src/processors/tone/AmpIRs.h
- src/processors/tone/LofiIrs.cpp
- src/processors/tone/LofiIrs.h
> Fix gain normalization at different sample rates for convolution-based modules

- src/gui/pedalboard/editors/ProcessorEditor.cpp
- src/processors/BaseProcessor.cpp
- src/processors/BaseProcessor.h
- src/processors/other/Tremolo.cpp
- src/processors/other/Tremolo.h
- src/processors/utility/StereoMerger.cpp
First draft at the modulation ports for the Tremolo module. Seems like pretty basic changes, and there are definitely different ways to approach some of the way the ports are labeled, so let me know if you have any ideas for that.
> Initial attempt at recognizing modulation ports

- src/gui/pedalboard/BoardComponent.cpp
- src/gui/pedalboard/BoardComponent.h
- src/gui/pedalboard/editors/KnobsComponent.cpp
- src/gui/pedalboard/editors/KnobsComponent.h
- src/gui/pedalboard/editors/ProcessorEditor.cpp
- src/gui/pedalboard/editors/ProcessorEditor.h
- src/processors/BaseProcessor.cpp
- src/processors/BaseProcessor.h
- src/processors/chain/ProcessorChain.cpp
- src/processors/other/Tremolo.cpp
- src/processors/other/Tremolo.h
- src/processors/utility/CleanGain.h
- src/processors/utility/FreqBandSplitter.cpp
- src/processors/utility/FreqBandSplitter.h
- src/processors/utility/Mixer.cpp
- src/processors/utility/Mixer.h
- src/processors/utility/StereoMerger.cpp
- src/processors/utility/StereoMerger.h
- src/processors/utility/StereoSplitter.cpp
- src/processors/utility/StereoSplitter.h
- Naming port indexes for multi-input / multi-output processors
- Tweaks and fixes for Tremolo modulation (forgot about bypass case, whoops)
- Add "Invert" option to Clean Gain processor
- Disable relevant UI controls when modulation input is connected
> Ports and Modulation updates

- modules/CMakeLists.txt
- res/presets/American Sound.chowpreset
- sim/Blonde/blonde_drive.py
- src/CMakeLists.txt
- src/processors/ProcessorStore.cpp
- src/processors/drive/BlondeDrive.cpp
- src/processors/drive/BlondeDrive.h
- src/processors/drive/RangeBooster.cpp
- src/processors/tone/BlondeTone.cpp
- src/processors/tone/BlondeTone.h
> Add emulations of circuits from American Sound pedal

- CHANGELOG.md
- src/CMakeLists.txt
- src/headless/tests/ParameterSmoothTest.cpp
- src/processors/BufferHelpers.h
- src/processors/ProcessorStore.cpp
- src/processors/other/Octaver.cpp
- src/processors/other/Octaver.h
> Add Octaver module

- .github/workflows/auto-format.yml
- src/BYOD.cpp
- src/gui/utils/HostContextProvider.cpp
- src/headless/tests/PresetsTest.cpp
- src/processors/chain/ProcessorChain.cpp
- src/processors/chain/ProcessorChain.h
- src/processors/chain/ProcessorChainStateHelper.cpp
- src/processors/drive/junior_b/JuniorB.cpp
- src/processors/modulation/phaser/Phaser4.cpp
- src/processors/modulation/phaser/Phaser8.cpp
> Fix crash when loading plugin state in iOS GarageBand

- src/headless/tests/AmpIRsSaveLoadTest.cpp
- src/processors/tone/amp_irs/AmpIRsSaveLoad.cpp
> Fix AmpIRs loading IRs from wav file on Linux

- src/CMakeLists.txt
- src/gui/pedalboard/BoardComponent.cpp
- src/gui/pedalboard/BoardComponent.h
- src/gui/pedalboard/editors/EditorSelector.cpp
- src/gui/pedalboard/editors/EditorSelector.h
- src/gui/pedalboard/editors/ProcessorEditor.cpp
- src/processors/chain/ProcessorChainActionHelper.cpp
- src/processors/chain/ProcessorChainActionHelper.h
> Add lasso for selecting multiple editors, and setting up actions for moving or deleting multiple editors at once

- src/gui/pedalboard/editors/Port.cpp
- src/gui/pedalboard/editors/ProcessorEditor.cpp
- src/headless/tests/BadModulationTest.cpp
- src/processors/BaseProcessor.cpp
- src/processors/BaseProcessor.h
- src/processors/modulation/Chorus.cpp
- src/processors/modulation/Flanger.cpp
- src/processors/modulation/Panner.cpp
- src/processors/modulation/Rotary.cpp
- src/processors/modulation/Tremolo.cpp
- src/processors/modulation/phaser/Phaser4.cpp
- src/processors/modulation/phaser/Phaser8.cpp
- src/processors/modulation/scanner_vibrato/ScannerVibrato.cpp
- src/processors/modulation/uni_vibe/UniVibe.cpp
Refactoring of modulation port handling and introduction of more general port handling to accommodate level I/O ports
> Level Ports

- src/processors/other/Compressor.cpp
- src/processors/other/Compressor.h
Methods that handle audio I/O processing updated to also handle level I/O processing
> Compressor Level Tracking

- src/processors/other/Gate.cpp
- src/processors/other/Gate.h
Methods that handle audio I/O processing updated to also handle level I/O processing
> Gate Level Tracking

- src/processors/other/EnvelopeFilter.cpp
- src/processors/other/EnvelopeFilter.h
Methods that handle audio I/O processing updated to also handle level I/O processing
> Envelope filter level tracking

- src/processors/BaseProcessor.cpp
- src/processors/BaseProcessor.h
- src/processors/chain/ProcessorChain.cpp
> Still process MIDI Modulator when output is not connected
